src/Settings.vala
src/SlingshotView.vala

Fixes https://bugs.launchpad.net/slingshot/+bug/1248484 and removes an implicit Gala dependency
This seems to have no effect on the ability to use Slingshot with a hotcorner

Remove references to Gala hotcorner settings

---

src/Widgets/AppEntry.vala

Let's check if our the AppStream Component ID is not empty so we don't call `uninstall` on the AppCenter DBus with empty ID.

Check if we have AppStream component ID

---

lib/synapse-core/desktop-file-service.vala

Fixes #7.
Puts the user data directory first in the data_dirs and checks if we already have the same desktop ID in the list, if yes, don't add a duplicate.

Fix duplicated entries in the search view

---

CMakeLists.txt

fedora has just introduced stricter linker flags, and it turns out, slingshot was missing the flag to be linked against libm.

CMakeLists.txt: add missing -lm linker flag

---

src/Backend/App.vala

Apps should declare their icon, we shouldn't be doing some fallback there but only the generic-application one

App: Remove fallback icon check for apps

---

src/Widgets/SearchView.vala

Fixes #95.
Allows to cycle search results with arrows. Creating another class just for this is required to override the `move_cursor` virtual signal and to access the base class.

Allow to cycle the search results with arrows

---

lib/synapse-core/desktop-file-service.vala

Recognize Cinnamon as a Gnome environment.
Is a separate environment enum entry required?

Silence warning re unrecognized X-Cinnamon environment.

---

src/SlingshotView.vala

Instead of showing only the app entries, show the entire grid so that the page switcher also appears correctly on the first launch.
There is a possibility that this could fix #112.

Fix page switcher not appearing first time when opening

---

src/Slingshot.vala

ISSUE:
Applications menu wingpanel indicator being displayed in login screen (greeter).
Users can for example open file manager and do read write operations **without** even loggin in.
EXPLAINATION:
Elementary lightdm greeter project at <https://github.com/elementary/greeter>   
file `src/Indicators/IndicatorBar.vala` calls  
`Wingpanel.IndicatorManager.get_default ().initialize (Wingpanel.IndicatorManager.ServerType.GREETER);`
and displays all the indicators in the IndicatorManager which means all the indicators meant for ServerType GREETER.
the `initialize` method of Wingpanel.IndicatorManager in project <https://github.com/elementary/wingpanel> iterates through all the installed indicators and calls `get_indicator` method on each. The indicators whose `get_indicator` method return a …

prevent indicator from appearing in greeters

---

data/pantheon-applications.menu

Evince recently renamed this to the [app-id](https://gitlab.gnome.org/GNOME/evince/commit/47136ec9deb5d0a99125864107426cbc6ac0c38a) so in gnome 3.30 this was no longer hidden.

Hide org.gnome.Evince.desktop

---

lib/synapse-plugins/switchboard-plugin.vala

See: #94 
While this gives us a quick win that doesn't require changes in Switchboard or all the Plugs it feels a bit fragile and technically unintuitive. An alternative approach would be adding an extra field to Switchboard.Plug that's used by the applications-menu. 
It can give a lot of results so maybe I should alter the matching logic in such a way that it doesn't include the root name in the matching.

Include sub settings in search results

---

lib/synapse-plugins/switchboard-plugin.vala

- Retaining more potential results
- More specific matching limiting actual results
This is an improvement on: https://github.com/elementary/applications-menu/pull/133
Started by some discussions at: https://github.com/elementary/switchboard-plug-keyboard/pull/176#issuecomment-426469609
I don't like the "default" results, not sure what to do about that. 
Maybe set a limit on the amount of results for the switchboard plugin? But that seems a bit arbitrary.

Refined sub settings search

---

src/SlingshotView.vala

Looks like for some reason populate_grid_view was resetting the category to the "normal" view when the application menu was opening.
No clue why it was added? 
Fixes: #146

Remove set to normal mode

---

src/Slingshot.vala

This drops the shortcut to a new line, makes it a little smaller, sets the opacity to 75%, and sets the weight to 600.

Style the tooltip a bit

---

src/Slingshot.vala

Start listening for keyboard shortcut change when indicator is created (`get_display_widget`), as apposed to only after the menu has been opened (`get_widget`). Making sure the tooltip is always up to date.

Fix tooltip update

---

CMakeLists.txt
README.md
src/Slingshot.vala

I noticed the current tooltip would only be added when a accelerator was set. So I've switched to using the latest Granite accel utils where accels are optional and it always shows the description. 
But while doing this I noticed that when the keyboard shortcut was set to disabled `keybinding_settings.get_strv ("panel-main-menu");` would return an array with an empty string. This caused the original granite-accels to look like this when the shortcut was disabled:
To fix this it now ignores empty keybindings.

Handle disabled Applications menu keyboard shortcut in tooltip

---

data/meson.build

We've had Prefix-dependent defaults for sysconfdir since meson 0.44
so this is always preferred.

Meson: install applications.menu using sysconfidr

---

src/Widgets/Grid.vala

* Reduce variable scope where possible
* Organize
* White space
* Remove fake grid. It doesn't seem to make a difference since other widgets are set to expand

Grid: misc cleanup

---

src/Backend/AppCenter.vala

Should probably fix https://github.com/elementary/wingpanel/issues/196 and #190.
Do not connect to the AppCenter DBus synchronously and try to reconnect to it every 5 seconds if we fail. This will prevent from AppCenter waiting forever for the DBus to come up which can be quite a long time since AppCenter needs to collect all installed packages.
I noticed this accidentally when I got `AppEntry.vala:299: Exceeded waiting time` (the message is translated).

Relax how app menu connects to the AppCenter DBus

---

src/Widgets/SearchView.vala

Using Idle.add () makes its actual launching occur after `drag_begin` signal is processed, so dragging from the search result no more launch the app.
Fixes #199.
This seems to work, but I am new to Vala / GTK so I don't know this use of Idle.add () is valid or not.  Also this fix assumes `drag_begin` signal is emitted before the idle function call. I don't know this is always true.

Use Idle.add () to launching app in SearchView

---

src/Backend/AppCenter.vala
src/Widgets/AppEntry.vala

Prevents wingpanel from being unresponsive if AppCenter itself hangs

AppCenter: make the DBus calls asynchronous

---

debian/control

It was removed a while ago in
* https://github.com/elementary/applications-menu/commit/985b050e0119e947d04e8cad09d1d706d58994e4

debian: drop Wnck

---

src/Backend/App.vala

We don't need Unity for this since 2012

App: get keywords from GLib.DesktopAppInfo

---

src/Widgets/CategoryView.vala

`add_app` is only ever used here, so no need for a separate method

CategoryView: Remove single-use method

---

src/Widgets/Sidebar.vala

* Organize
* Use `construct`
* Use Gtk style constant
* Reduce method scope
* Brackets and whitespace

Sidebar: code style cleanups

---

src/Views/CategoryView.vala
src/Widgets/Sidebar.vala

* Remove unused `current_position` (we only ever set it to 0)
* Remove unused `name` from `selection_changed` signal

CategoryView: Remove unused variables

---

src/Widgets/SearchItem.vala

* Explicitly mark iconsize as private
* Group private variables
* Remove unnecessary cast
* grid is horizontal by default

SearchItem: minor misc cleanup

---

src/SlingshotView.vala

Pressing `Ctrl` always focuses the search entry so this is never actually used

SlingshotView: Remove redundant paste handler

---

.github/FUNDING.yml
src/Widgets/AppContextMenu.vala

Fixes https://github.com/elementary/applications-menu/issues/31 
Will work for all apps with valid component id when https://github.com/elementary/appcenter/pull/1078 is fixed. 
Doesn't show for snaps, appimages and apps invalid component id.

Add View in Appcenter menuitem

---

src/Widgets/AppContextMenu.vala

* Make strings translatable
* Use app icon
* Explain possible unknown side effects of the action
* Affirmative action is labeled with the action it performs (not "Yes" or OK")
* Avoid an unnecessary `show_all` with `add_button`
* Stick since the user could change workspaces and lose the dialog but be unable to interact with anything else on screen

Localization, icons, etc

---

src/synapse-plugins/command-plugin.vala

Reverts elementary/applications-menu#284
Turns out this breaks actions

Revert "CommandPlugin: Change to Action type"

---

src/Widgets/AppContextMenu.vala

This is unnecessary because it exists in a clause that depends on appcenter's dbus API existing and the `open_in_appcenter` method has a try/catch already for opening an appstream URI (which doesn't depend on AppCenter specifically anyways)

AppContextMenu: Remove extra check for appcenter

---

src/SlingshotView.vala
src/Views/GridView.vala

Always propagate this keypress event and deal with it only when the grid view is focused

Move Home shortcut to GridView

---

meson.build
src/Views/SearchView.vala
src/meson.build
src/synapse-plugins/switchboard-plugin.vala
src/synapse-plugins/switchboard-plugin/plugin.vala
src/synapse-plugins/worker-link.vala

This allows to put all the switchboard compatibility layer in a throwable subprocess and thus allow to keep all the Switchboard-related components in the subprocess only.

Switchboard: Put switchboard loading in a separate process

---

src/SlingshotView.vala

This doesn't make sense because we already propagate this keypress if the view isn't grid view. If the search entry has any text in it, it is always the search view

SlingshotView: remove check for search length on end key

---

data/applications-menu.appdata.xml.in
src/SlingshotView.vala

Fixes an issue where pressing modifier keys (like shift) automatically throws focus to the searchbar which makes it impossible to use shortcuts like shift + → to switch pages in grid view

SlingshotView: Don't pass mod keys to search

---

meson.build
meson_options.txt
src/meson.build

Usage of `libunity` seems to have been dropped from slingshot at some point, but the build system scaffolding for it is still there. I found no usage of `HAVE_UNITY` in the project's vala files.
- remove the `with-unity` meson option
- remove the optional `unity` dependency from meson.build files
Additionally, clean up the redundant check for `zeitgeist`, which makes it not really optional at all (since it's checked once outside the optional block, and once inside the `with-zeitgeist` option).
Fixes: #384
So: Looks like #251 has already been fixed (but not closed yet) and this PR just serves as a small cleanup afterwards :)

meson: clean up superfluous unity dep and make zeitgeist dep really optional

---

src/synapse-plugins/calculator-plugin.vala

Fixes #414 
It seems unnecessary to drop the mathlib parameter and it caused the linked issue.

Revert dropping math lib; caused truncation in division

---

src/synapse-plugins/switchboard-plugin.vala

Fixes a terminal warning (with Gtk3)

Switchboard-plugin.vala: Use AppInfo.launch_default_for_uri ()

---

src/Views/GridView.vala

Fixes a compile warning.
No particular reason to use same function name as parent.

GridView.vala: Use non-clashing function name

---

src/synapse-core/desktop-file-service.vala
src/synapse-plugins/desktop-file-plugin.vala

There seems to be a bunch of code here that's supposed to offer up an application if you provide a URI/mime and there's a desktop file that reports it supports opening that.
However... there's a condition right at the top of the method here that says:
https://github.com/elementary/applications-menu/blob/9ee21f7e9d51957456ee1de86ab971dc785c85c2/src/synapse-plugins/desktop-file-plugin.vala#L352
`mime_type` is never set anywhere, so it's always `null`. In fact, I'm not sure we're even constructing a `UriMatch` class anywhere. So we have a bunch of code in `DesktopFileService` that parses all of the mimes that everything supports and caches it in RAM, then nothing that ever uses that information.
So, if we drop all that, we can save some RAM, CPU cycles and disk I/O.

DesktopFilePlugin: Remove unused mime support

---

src/synapse-core/desktop-file-service.vala

Fixes a couple of warnings in the console about LXQt and ubuntu not being known session types and recognises the fact that Ubuntu now uses GNOME instead of Unity.
Also replaces the manual numbering of the flags, `0x3FF` was wrong anyway :wink:

DesktopFileService: Update desktop environments

---

src/Widgets/SearchItem.vala

Gets rid of some critical spam you get in the terminal when you get a search result that contains a terminal program (`cat`, `less`, `top`, etc...)

SearchItem: null check AppInfo filename

---

src/synapse-core/desktop-file-service.vala

Replace all the manual directory enumeration, watching, parsing and re-parsing of desktop files with `GLib.AppInfoMonitor` and `GLib.AppInfo.get_all`.
This partially solves the issue of #440 . First-time flatpaks will now appear when you search for them, but not yet in the "browse" views. It may also help with #182 
The major benefit is the much simpler code however. The diff looks scary and looks like it changes everything, but it's mostly just changing the usage of `KeyFile` to the built-in keyfile operations on `GLib.AppInfo` and deleting cruft.
To test, search for some apps and check they appear as they did before.

DesktopFileService: Rewrite using GLib AppInfoMonitor

---

src/Widgets/AppContextMenu.vala

Fixes #423 
Instead of waiting to pack these menuitems until after dbus connects, we always pack them if AppCenter is installed and set sensitivity when dbus connects

AppContextMenu: Always add AppCenter items

---

src/Views/SearchView.vala

This is now handled in the stylesheet

SearchView: Remove redundant header margin

---

src/synapse-plugins/worker-link.vala

The AppArmor profile allows to use this prefix for abstract sockets
closes https://github.com/elementary/applications-menu/issues/393

WorkerLink: Use the dbus- prefix to work in the guest session

---

meson.build
src/Config.vala.in
src/Indicator.vala
src/meson.build
src/synapse-plugins/switchboard-plugin/plugin.vala

Provides the directory where the locales are actually installed.
We are [packaging this](https://github.com/NixOS/nixpkgs/pull/130380#issuecomment-895720580) in NixOS, and due to NixOS 's special `localedir`, we cannot apply the translations without this patch.
Thanks in advance for reviewing this :-)

l10n: Correctly setup the locales

---

data/applications-menu.appdata.xml.in
meson.build

Fixes a regression caused by switching from LibGNOMEMenu that affects webapps created by Chrome and maybe some other kinds of manually created desktop files

Release 2.8.2

---

debian/control

debian: Remove unused appstream dependency

---

src/synapse-plugins/file-bookmarks-plugin.vala

Since we're using `launch_defualt_for_uri` and not for sure launching with Files, let's make sure to try to find out what the actual default app is

Bookmarks Plugin: Get default file browser name

---

src/synapse-plugins/calculator-plugin.vala
src/synapse-plugins/calculator-plugin/calculator-plugin-backend.vala
src/synapse-plugins/calculator-plugin/calculator-plugin.vala
src/test/PluginTest.vala

Fixes #474 
Fixes #439
- Accept a wider range of valid `bc` expressions, including concatenated expressions
- Accept number base and scale expressions
- Reject capitals if no number base expression
- Require at least one numeric expression when not using hexadecimal
- Show the actual result returned by `bc`, not a limited precision floating point number.
It is still rarely possible to enter strings that are not mathematical expressions that get passed to `bc` and give a spurious result but to completely prevent this while allowing a wide range of valid expressions is too complex to be worthwhile (at least not in this PR).

Improve calculator plugin

---

src/synapse-plugins/converter-plugin/converter-plugin-backend.vala
src/test/ConverterPluginTest.vala

As discussed in previous PR, this PR implements using capturing groups in the regex to isolate parts of the input without having to use string processing in the code.  Minor improvements to the regex were also made, allowing localized input of non-Latin characters to be matched.

Use regex to parse conversion plugin input

---

.github/workflows/githubci.yml
README.md
src/Views/CategoryView.vala

We no longer use gnome-menus (#496) and removed it from deb-packaging too (706d383a910670c71248c19562a983b38f70398f) so `dgettext ("gnome-menus-3.0", cat_name)` does nothing here.
Confirmed this change does not affect to the localized category text:
Also reviewed dependencies list in GitHub Actions and README while I'm here.

CategoryView: Remove no longer used dgettext

---

src/synapse-plugins/calculator-plugin/calculator-plugin-backend.vala
src/synapse-plugins/calculator-plugin/calculator-plugin.vala
src/test/CalculatorPluginTest.vala

Fixes #566 
Instead of using a regex to match the whole of the input, each component expression is checked for validity using a procedure. 
For now, for simplicity, use of variables is disallowed.  It would be possible to allow variables at the cost of more code complexity if it was thought worth it in this context.
Apart from variables the capabilities should be the same as in master.
All the expressions passed by the procedure *should* give a valid result when passed to `bc`.
An additional check is made compared to `master` (or `bc`) which is that if an ibase is set then invalid digits for that base are excluded.

Replace regex with procedure

---

src/synapse-core/data-sink.vala
src/synapse-plugins/appcenter-plugin.vala
src/synapse-plugins/calculator-plugin/calculator-plugin.vala
src/synapse-plugins/command-plugin.vala
src/synapse-plugins/converter-plugin/converter-plugin.vala
src/synapse-plugins/desktop-file-plugin.vala
src/synapse-plugins/file-bookmarks-plugin.vala
src/synapse-plugins/link-plugin.vala
src/synapse-plugins/switchboard-plugin.vala
src/synapse-plugins/system-managment.vala

These properties are unused and can be removed.

Simplify PluginInfo

---

src/synapse-plugins/file-bookmarks-plugin.vala

Also several cleanups regarding the code surrounding the GLib.FileInfo usage.

Make sure to always query the right info before use

---

src/Widgets/AppContextMenu.vala

Fixes https://github.com/elementary/applications-menu/issues/620
Fixes https://github.com/elementary/applications-menu/issues/621
Ive tested both changing state in the dock and appmenu, for several apps, several times - it works.
Second commit removes usage of the "docked" variable, state would be tracked by the checkmenuitem state - more variables to keep in sync means more variables to keep track of and more opportunities for bugs down the line.
If you prefer keeping it, first commit works on its own.
i hope there arent too much new comments ? Needed to understand how its done and navigate. It may make the file new friendly for new contributors, but should have been its own separate commit.

Consistency improvement with dock menu item

---

src/Widgets/AppContextMenu.vala

I don't love using a verbal phrase with a checkbox. Use the same label as we use in the Dock.

AppContextMenu: change keep in dock label

---

src/Widgets/AppContextMenu.vala

Gtk.MenuItem is removed in GTK4. First step to replacing it with a menu model is to use GLib.Action for menu items

AppContextMenu: Use GLib.Action

---

src/SlingshotView.vala

This was added to fix https://bugs.launchpad.net/slingshot/+bug/1498386 but this was when we had a bunch of other stuff to calculate grid size etc that we no longer have

SlingshotView: remove dead get_screen

---

src/SlingshotView.vala
src/Views/CategoryView.vala

Use GTK's built-in method for determining if a key event should be handled by the search entry. Should prevent keypress stealing and unnecessary focus shifting

SlingshotView: use SearchEntry.handle_event

---

src/Views/GridView.vala

while here, switch to `get_default_direction ()` because getting style context is deprecated

GridView: use KeyController

---

src/Widgets/AppContextMenu.vala

AppContextMenu: use dialog response/present

---

data/PageChecker.css

Fixes a regression introduced in #666 
Turns out we don't have keyboard focus styles for modelbuttons in GTK3

Styles: add modelbutton focus style
