src/Backend/AppSystem.vala

Fix a regression appeared in 7260b2148c2cd644fa084af6bc2e5ea3a949a3eb

Fix some categories not appearing

---

po/slingshot.pot

We should update translation template because "Uninstall" string is not translatable.

Update translation template

---

src/Widgets/SearchView.vala

Updates Free Software Foundation address in license header.
Fixes https://bugs.launchpad.net/slingshot/+bug/1653413

Update FSF address

---

src/Backend/SynapseSearch.vala
src/Widgets/SearchItem.vala

before: (no icons if `Icon=/path/to/image` in `.desktop`)
after:

Load icons with absolute URI (Close #36)

---

src/SlingshotView.vala
src/Widgets/Grid.vala

Fixes #1 
This implements the scroll delay code from Gala to only scroll one page per swipe

Only swipe one page at a time

---

src/Slingshot.vala

Quick and dirty, probably not doing this the most perfect way.

Add icon to indicator

---

src/Slingshot.vala

Fixes #59 
Needs code added to parse system settings from `/org/pantheon/desktop/gala/behavior/panel-main-menu-action`

Add a tooltip

---

src/Widgets/AppEntry.vala

* Check if the badge is actually greater than 0
* Put lambdas into their own method 
(Fixes #74?)

Do not display badges when their count is 0

---

src/Widgets/AppEntry.vala

Use the icon from the application object instead of the asyncimage

---

src/Widgets/AppEntry.vala

https://github.com/elementary/applications-menu/issues/108

fix the Uninstall option is disappearing

---

.travis.yml
CMakeLists.txt
README.md
src/Slingshot.vala

Use Granite for accels

---

src/Widgets/CategoryView.vala

* GObject-style
* Reduce variable scope
* Remove single-use method
* Organize
* Remove unused constants and single-use constant

CategoryView: GObject-style, misc cleanup

---

meson.build
src/Widgets/AppEntry.vala

fix build without unity

---

lib/synapse-plugins/appcenter-plugin.vala
lib/synapse-plugins/link-plugin.vala

Fix some strings are not shown as translated

---

.travis.yml
README.md

It was removed a while ago in
* https://github.com/elementary/applications-menu/commit/985b050e0119e947d04e8cad09d1d706d58994e4

Don't Mention Wnck in README.md etc.

---

src/Widgets/Grid.vala

Nothing too crazy here, just hitting low hanging fruit.

Grid: appropriately scope methods

---

src/SlingshotView.vala

* Organize and code style
* Reduce variable scope
* Remove redundant margins

Remove setup_ui method and clean up

---

CMakeLists.txt
meson.build
src/Backend/App.vala
src/Slingshot.vala
src/SlingshotView.vala
src/Widgets/AppEntry.vala

Drop support for Plank <0.11

---

lib/synapse-core/meson.build
lib/synapse-plugins/meson.build

Don't install static libraries

---

src/Backend/AppSystem.vala
src/SlingshotView.vala

We never do anything with this

AppSystem: remove unused get_categories

---

src/SlingshotView.vala

Make things a bit less of a mess so its easier to find public variables
Also use `construct`

SlingshotView: organize variables

---

po/POTFILES
src/Indicator.vala
src/SlingshotView.vala
src/meson.build

Also update copyright header and remove unused `icon_theme` while we're here

Move and re-namespace Slingshot.Slingshot to Slingshot.Indicator

---

src/Backend/AppSystem.vala

* white space
* brackets
* reduce method scope

AppSystem: misc cleanup

---

src/Views/SearchView.vala

View with no whitespace changes :)

SearchView: Inline namespacing

---

src/SlingshotView.vala

View with no whitespace changes :)
Also update copyright header and reduce the scope of `modality` enum

SlingshotView: inline namespace

---

src/Backend/App.vala

* GObject style
* Remove unused `IconError`
* Remove unused properties
* Avoid unassigned properties. Mark nullables
* DRY fallback icon fetching

App: GObject style and cleanup

---

src/Backend/App.vala

Reverts elementary/applications-menu#245
Turns out this branch makes everything crash

Revert "App: GObject style and cleanup"

---

src/Widgets/SearchItem.vala

review with no whitespace changes

SearchItem: Inline namespace

---

po/POTFILES
src/SlingshotView.vala
src/Views/CategoryView.vala
src/Views/GridView.vala
src/Widgets/AppButton.vala
src/meson.build

Make it clearer that this is a button subclass

Rename AppEntry to AppButton

---

src/SlingshotView.vala

So we can tell WTF is happening

SlingshotView: Use Gdk.EVENT constants

---

src/SlingshotView.vala

Only check things once, no single-use methods

SlingshotView: Simplify view switch shortcut

---

src/Views/SearchView.vala
src/Widgets/AppListBox.vala
src/meson.build

I want to re-use this for making the category view a list

Move CycleListBox to its own class

---

src/SlingshotView.vala

* Check for a positive, not a negative
* Only parse key if we're going to use it
* Add brackets
* Only return stop if we actually use the keyboard shortcut

Slingshotview: Cleanup page switch shortcut

---

lib/synapse-plugins/command-plugin.vala

CommandPlugin: Change to Action type

---

src/Widgets/SearchItem.vala

Fixes https://github.com/elementary/applications-menu/issues/283

Fix app actions' markup

---

src/Backend/SynapseSearch.vala
src/Widgets/SearchItem.vala

Only ever used in this class, so move it here

Move search string markup to SearchItem

---

src/Backend/AppSystem.vala
src/Backend/RelevancyService.vala
src/Backend/SynapseSearch.vala
src/Indicator.vala
src/SlingshotView.vala
src/Views/GridView.vala

To test locally:
`docker run -v "$PWD":/app valalang/lint:latest io.elementary.vala-lint -d src`
`io.elementary.vala-lint -d src`
_**note: I have not resolved the "note" errors that valalint reports.**_

Lint src directory with vala-lint.

---

src/SlingshotView.vala

Noticed that Alt+Num page switching wasn't working. This fixes it.

Fix Alt page switching

---

lib/synapse-core/common-actions.vala
lib/synapse-core/config-service.vala
lib/synapse-core/data-sink.vala
lib/synapse-core/desktop-file-service.vala
lib/synapse-core/query.vala
lib/synapse-core/relevancy-backend-zg.vala
lib/synapse-core/utils.vala
lib/synapse-core/volume-service.vala
lib/synapse-plugins/appcenter-plugin.vala
lib/synapse-plugins/calculator-plugin.vala
lib/synapse-plugins/command-plugin.vala
lib/synapse-plugins/desktop-file-plugin.vala
lib/synapse-plugins/link-plugin.vala
lib/synapse-plugins/switchboard-plugin.vala
lib/synapse-plugins/system-managment.vala

To test locally:
`docker run -v "$PWD":/app valalang/lint:latest io.elementary.vala-lint -d lib`
`io.elementary.vala-lint -d lib`
_**note: I have not resolved the "note" errors that valalint reports.**_

Lint lib directory with vala-lint.

---

lib/synapse-core/data-sink.vala

DataSink: NUM_COMPONENTS → num_components

---

src/Widgets/AppContextMenu.vala

Since error handling will be done AppCenter this pr is ready for review.

Add Uninstall Comfirmation Dialog

---

src/synapse-plugins/appcenter-plugin.vala

Strip search text in AppCenter listing

---

src/synapse-core/Actions/BaseAction.vala
src/synapse-core/Matches/DefaultMatch.vala
src/synapse-core/Matches/Match.vala
src/synapse-plugins/appcenter-plugin.vala
src/synapse-plugins/calculator-plugin.vala
src/synapse-plugins/command-plugin.vala
src/synapse-plugins/desktop-file-plugin.vala
src/synapse-plugins/link-plugin.vala
src/synapse-plugins/switchboard-plugin.vala
src/synapse-plugins/system-managment.vala

Allows to reduce the duplication and adding features will then be easier

Synapse: Make Match an abstract class instead of an interface

---

data/applications-menu.appdata.xml.in
meson.build

Reverts elementary/applications-menu#325

Revert "Release 2.5.0"

---

data/applications-menu.appdata.xml.in
meson.build

https://github.com/elementary/applications-menu/compare/2.4.4...master
Where required, I've:

Release 2.5.0

---

src/Pixels.vala
src/SlingshotView.vala
src/Views/GridView.vala

SlingshotView: Remove height request

---

src/SlingshotView.vala
src/Views/CategoryView.vala

Shift shortcuts don't seem to work in master either, so moving this code is theoretical I guess. This branch doesn't solve that issue.

SlingshotView: Fix moving down from searchbar in category view

---

src/SlingshotView.vala
src/Views/GridView.vala

Allows us to simplify things a bit

Make populate internal to GridView

---

src/Widgets/AppButton.vala

* Remove unused
* Organize
* Reduce scope
* GObject style

AppButton: GOBject style and cleanup

---

src/SlingshotView.vala
src/Widgets/Sidebar.vala

And use scroll direction constants

Sidebar: Remove broken scroll handling

---

meson.build
src/synapse-plugins/switchboard-plugin.vala
src/synapse-plugins/switchboard-plugin/plugin.vala

switchboard-plugin: Rename the plugins directory and fix type in Applications Menu name

---

data/applications-menu.appdata.xml.in
src/SlingshotView.vala
src/Views/CategoryView.vala

CategoryView: Focus searchbox if navigating up

---

src/Indicator.vala

Indicator: Make get_indicator nullable

---

src/SlingshotView.vala

Now that we've cleaned up a lot of junk and we're propagating keypresses in more places now, it's not clear that the complex event handling is needed anymore. All keyboard shortcuts seem to work as expected here.
Now we make sure to only handle things specific to the search entry there and all global shortcuts are handled in the eventbox handler
I made a comment pointing out which is the Alt condition, since it's not super clear
I also added a FIXME comment for a focus move that was unclear. I didn't add the workaround, just a comment about it

SlingshotView: Clean up some keypress signal handlers

---

src/Views/CategoryView.vala

Caching a row ID was wrong as it is immediatly reordered when ordering the categories by name.

CategoryView: Make sure that the content of the category we are using is always on-par with the selected row

---

data/applications-menu.appdata.xml.in
meson.build

Just localization updates, but it's been a month

Release 2.7.1

---

src/synapse-plugins/calculator-plugin.vala

Support fractions without leading number in calculator plugin

---

src/Views/CategoryView.vala

Goes with https://github.com/elementary/stylesheet/pull/779

CategoryView: fix sidebar style

---

src/SlingshotView.vala
src/Views/CategoryView.vala

Because creating and destroying widgets is wasteful

CategoryView: use filter_func instead of destroy

---

src/Backend/AppSystem.vala

Closes https://github.com/elementary/triage/issues/34

Hide terminal applications

---

src/Views/CategoryView.vala

Clear category view list box during setup

---

data/pantheon-applications.menu

Menu: Remove evince from blocklist

---

debian/control
debian/rules

It is now provided by the dbgsym package

Do not provide dbg package

---

debian/slingshot-launcher.install

Remove install file

---

po/zh_CN.po
src/Indicator.vala

Add super key gala shortcut to tooltip

---

src/Backend/Category.vala

Category: Sort apps without categories in desktop into other

---

src/synapse-plugins/switchboard-plugin/plugin.vala

This is required to use D-Bus.
Also use async variants when possible.

switchboard-plugin: Re-add a GLib.MainLoop

---

data/applications-menu.appdata.xml.in
po/extra/pl.po
src/synapse-plugins/switchboard-plugin.vala

Fixes #520 
Always search title

Always search title

---

.github/workflows/githubci.yml
.github/workflows/release.yml
data/applications-menu.appdata.xml.in
src/Indicator.vala

Fixes #546 
The same as https://github.com/elementary/switchboard-plug-keyboard/pull/406
Breaks OS 6 compatibility

Move panel-main-menu to Gala schema

---

README.md

For infrequent contributors and/or ninja users this is interesting information.

Add test instructions to readme

---

data/meson.build
meson.build
meson_options.txt
po/extra/meson.build
po/meson.build
src/meson.build
src/test/meson.build

* pkconfig variable
* `source_root`
* don't use `join_paths` while here and use directory variables
* string should be bool

Meson: fix deprecation warnings

---

README.md
meson.build
src/Backend/App.vala
src/Backend/Unity.vala
src/Indicator.vala
src/SlingshotView.vala
src/Widgets/AppButton.vala
src/meson.build

Uses the Unity backend from Dock to remove a Plank dep

Unity badges without Plank

---

src/Indicator.vala

https://github.com/elementary/gala/pull/2034

Use new behavior schema

---

.github/workflows/githubci.yml
README.md

Remove Unity dep

---

data/io.elementary.desktop.wingpanel.applications-menu.gschema.xml
src/SlingshotView.vala

No Modebutton in GTK4. According to GTK docs connecting to `toggled` is discouraged, use an action instead.

SlingshotView: Replace deprecated Granite.ModeButton

---

src/Widgets/AppButton.vala

* bump copyright header
* Instantiate with properties
* Replace grid with box
* use child property
* explicit h/vexpand

AppButton: GTK4 prep, code style

---

src/Views/CategoryView.vala

* Use SPDX header
* Code style
* use `child` property
* explicit hexpand/vexpand

CategoryView: code style, GTK4 prep

---

src/Widgets/SearchItem.vala

* Use SPDX header
* Code style
* Replace grid with box
* explicit margins
* use child property

SearchItem: Gtk4 Prep, Code Style

---

src/Views/GridView.vala
src/Widgets/Switcher.vala

* Use SPDX header
* Subclass Box instead of Grid
* use `carousel` instead of `paginator`
* make `carousel` a property
* use `n_pages` where possible
* call `show` on buttons instead of overriding `show` and `show_all`

Switcher: gtk4 prep

---

src/Widgets/SearchItem.vala

Never gets assigned :woman_shrugging: We can't override destroy in GTK4

SearchItem: remove unused cancellable

---

src/Widgets/Switcher.vala

In GTK4 we don't have `get_children`, so rewrite to use `n_pages` as much as possible.

Switcher: get_children, add.connect_after -> n_pages
